Repository coin-games/coin-game, pull requests merged in 2025-05, with the labels that each got.

#4 feat: Dockerize Spring + Vue with docker compose
  backend/.dockerignore
  backend/Dockerfile
  backend/build.gradle
  backend/gradlew
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/nginx.conf
Labels: project settings

#18 feat: 사용자 회원가입 / 로그인 기능 구현
  backend/build.gradle
  backend/src/main/java/com/cgs/backend/common/exception/BaseException.java
  backend/src/main/java/com/cgs/backend/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/cgs/backend/common/exception/UserException.java
  backend/src/main/java/com/cgs/backend/common/response/CustomResponse.java
  backend/src/main/java/com/cgs/backend/common/response/ResponseCode.java
  backend/src/main/java/com/cgs/backend/controller/AuthController.java
  backend/src/main/java/com/cgs/backend/controller/UserController.java
  backend/src/main/java/com/cgs/backend/dto/auth/TokenReissueRequest.java
  backend/src/main/java/com/cgs/backend/dto/user/TokenResponse.java
  backend/src/main/java/com/cgs/backend/dto/user/UserLoginRequest.java
  backend/src/main/java/com/cgs/backend/dto/user/UserSignUpRequest.java
  backend/src/main/java/com/cgs/backend/entity/User.java
  backend/src/main/java/com/cgs/backend/repository/UserRepository.java
  backend/src/main/java/com/cgs/backend/security/JwtAuthenticationFilter.java
  backend/src/main/java/com/cgs/backend/security/JwtProvider.java
  backend/src/main/java/com/cgs/backend/security/SecurityConfig.java
  backend/src/main/java/com/cgs/backend/security/TokenValidationResult.java
  backend/src/main/java/com/cgs/backend/service/auth/AuthService.java
  backend/src/main/java/com/cgs/backend/service/redis/TokenService.java
  backend/src/main/java/com/cgs/backend/service/user/UserLoginService.java
  backend/src/main/java/com/cgs/backend/service/user/UserSignUpService.java
  backend/src/main/resources/application-dev.yml
  backend/src/test/java/com/cgs/backend/service/auth/AuthServiceTest.java
  backend/src/test/java/com/cgs/backend/service/user/UserLoginServiceTest.java
  backend/src/test/java/com/cgs/backend/service/user/UserSignUpServiceTest.java
Labels: good first issue

#21 feat: @Transactional 추가, UUID 변경
  backend/src/main/java/com/cgs/backend/common/response/CustomResponseEntity.java
  backend/src/main/java/com/cgs/backend/controller/AuthController.java
  backend/src/main/java/com/cgs/backend/controller/UserController.java
  backend/src/main/java/com/cgs/backend/entity/User.java
  backend/src/main/java/com/cgs/backend/service/user/UserSignUpService.java
  backend/src/test/java/com/cgs/backend/controller/UserControllerTest.java
Labels: enhancement
